package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import domain.model.Category;



public class CategoryRepository extends BaseRepository {

	

		String insertSql = "INSERT INTO currency(name) VALUES (?)";
		String selectByIdSql = "SELECT * FROM people WHERE id=?";
		
		PreparedStatement insert;
		PreparedStatement selectById;
		
		public CategoryRepository(Connection connection) {
			super(connection);
			try
			{
				insert = connection.prepareStatement(insertSql);
				selectById = connection.prepareStatement(selectByIdSql);
			}
			catch(SQLException e)
			{
				e.printStackTrace();
			}
		}
		

		public Category get(int categoryId){
			try{
				selectById.setInt(1, categoryId);
				ResultSet rs = selectById.executeQuery();
				while(rs.next()){
					return Category.getByName(rs.getString("name"));
				}
				return null;
			}
			catch(SQLException ex){
				ex.printStackTrace();
				return null;
			}
		}
		
		public void add(Category category) {
			try {
				insert.setString(1, category.name());
				insert.executeUpdate();
			} catch (SQLException ex) {
				ex.printStackTrace();
			}
		}
		@Override
		protected String createTableSql() {
			return "" + "CREATE TABLE category("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
					+ "name varchar(5)," + ")";
		}

		@Override
		protected String tableName() {
			return "category";
		}
}
