package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import domain.model.Reader;

public class ReaderRepository extends BaseRepository {

	String insertSql = "INSERT INTO reader(firstName, lastName,phoneNumber,email,) VALUES (?,?)";
	String selectByIdSql = "SELECT * FROM people WHERE id=?";
	
	PreparedStatement insert;
	PreparedStatement selectById;
	
	public ReaderRepository(Connection connection) {
		super(connection);
		try {
			insert = connection.prepareStatement(insertSql);
			selectById = connection.prepareStatement(selectByIdSql);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Reader get(int readerId){
		try{
			selectById.setInt(1, readerId);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				Reader result = new Reader();
				result.setId(rs.getInt("id"));
				result.setFirstName(rs.getString("firstName"));
				result.setLastName(rs.getString("lastName"));
				result.setPhoneNumber(rs.getString("phoneNumber"));
				result.setEmail(rs.getString("email"));
				return result;
			}
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
		
	}
	
	public void add(Reader reader) {
		try {
			insert.setString(1, reader.getFirstName());
			insert.setString(2, reader.getLastName());
			insert.setString(3, reader.getPhoneNumber());
			insert.setString(4, reader.getEmail());
			insert.executeUpdate();
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE reader("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)" + ")";
	}

	@Override
	protected String tableName() {
		return "reader";
	}
}
