package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.Reader;

public class ReaderRepository extends BaseRepository<Reader> {

	public ReaderRepository(Connection connection, IMapResultSetIntoEntity<Reader> mapper) {
		super(connection,mapper);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE reader("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)," + "ADDRESS_ID"+")";
	}

	@Override
	protected String tableName() {
		return "reader";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO reader(firstName, lastName,phoneNumber,email,ADDRESS_ID) VALUES (?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE reader SET (firstName, lastName,phoneNumber,email,ADDRESS_ID)=(?,?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setUpdate(Reader entity) throws SQLException {
		update.setString(1, entity.getFirstName());
		update.setString(2, entity.getLastName());
		update.setString(3, entity.getPhoneNumber());
		update.setString(4, entity.getEmail());
		update.setObject(5, entity.getAddress());
		
	}

	@Override
	protected void setInsert(Reader entity) throws SQLException {
		insert.setString(1, entity.getFirstName());
		insert.setString(2, entity.getLastName());
		insert.setString(3, entity.getPhoneNumber());
		insert.setString(4, entity.getEmail());
		insert.setObject(5, entity.getAddress());
		
	}
}
